version: "3"
services:

  web1:
    image: nginx
    container_name: cont-2
    ports:
      - "81:80"

  web2:
    image: tomcat
    container_name: cont-3
    ports:
      - "8082:8080"

  web3:
    image: durgaprasaduniq/project-1:v3
    container_name: cont-4
    ports:
      - "8083:80"
